version: 0.2
env:
  variables:
    S3_BUCKET: "handy-go"
    PACKAGE: "github.com/ztsu/handy-go"

phases:
  install:
    commands:
      - mkdir -p "/go/src/$(dirname ${PACKAGE})"
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/${PACKAGE}"
      - env
      - go get -u github.com/golang/lint/golint
      - go get -u github.com/aws/aws-lambda-go/events github.com/google/uuid go.etcd.io/bbolt

  pre_build:
    commands:
      - cd "/go/src/${PACKAGE}"
      - golint -set_exit_status

  build:
    commands:
      - GOOS=linux GOOS=linux go install github.com/ztsu/handy-go/cmd/handy-lambda-decks github.com/ztsu/handy-go/cmd/handy-lambda-cards
      - cp /go/bin/handy-lambda-decks /go/bin/handy-lambda-cards `pwd`
      - ls -la
      - aws cloudformation package --template-file template.yml --s3-bucket ${S3_BUCKET} --output-template-file packaged-template.yml

artifacts:
  type: zip
  files:
    - template.yml
    - packaged-template.yml
