version: 0.2
env:
  variables:
    S3_BUCKET: "handy-go"
    PACKAGE: "github.com/ztsu/handy-go"

phases:
  install:
    commands:
      - mkdir -p "/go/src/$(dirname ${PACKAGE})"
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/${PACKAGE}"
      - env
      - go get -u github.com/golang/lint/golint
      - go get -u github.com/aws/aws-lambda-go/events

  pre_build:
    commands:
      - pwd
      - ls /go
      - ls /go/bin
      - cd "/go/src/${PACKAGE}"
      - go install ./...
      - go get -t ./...
      - golint -set_exit_status
      - go vet .
      - go test .

  build:
    commands:
      - GOOS=linux GOOS=linux go build
      - cp /go/bin/decks /go/bin/cards `pwd`
      - ls -la
      - aws cloudformation package --template-file template.yml --s3-bucket ${S3_BUCKET} --output-template-file packaged-template.yml

artifacts:
  type: zip
  files:
    - template.yml
    - packaged-template.yml
