// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type CreateDeck struct {
	Name string `json:"name"`
}

type Deck struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	User *User  `json:"user"`
}

type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type RegisterUserInput struct {
	Email string `json:"email"`
}

type RegisterUserOutput struct {
	Ok     bool     `json:"ok"`
	User   *User    `json:"user"`
	Errors []*Error `json:"errors"`
}

type User struct {
	ID    string `json:"id"`
	Email string `json:"email"`
}
