// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type MathMutation struct {
	Inc int `json:"inc"`
	Dec int `json:"dec"`
}

type RegisterUser struct {
	Email string `json:"email"`
}

type User struct {
	ID    string `json:"id"`
	Email string `json:"email"`
}
